name: AntiAdvertising
main: de.upsj.advertising.AntiAdvertisingPlugin
description: Kicking server advertisers
version: 1.2
author: upsj
commands:
  AntiAdvertReload:
    Usage: '/<command>'
    permission: AntiAdvertising.reload
permissions:
  AntiAdvertising.*:
    children:
      AntiAdvertising.reload: true
      AntiAdvertising.ignore: true
      AntiAdvertising.notify: true
    default: op
  AntiAdvertising.reload:
    description: Permission to reload the configuration
  AntiAdvertising.ignore:
    description: Permission to ignore advertising check
  AntiAdvertising.notify:
    description: Permission to be notified about advertising